import { Platform } from 'react-native';
import { useIncomingCallStore, IncomingExpressVetCallPayload } from '../stores/incomingCallStore';

/**
 * iOS-only native ringing-call UI for the Vets at Home / Express Vet dispatcher alert, via
 * react-native-callkeep -> CallKit. The OS itself owns the ringing/vibration/lock-screen
 * behavior once a call is displayed — there is no ringtone-loop or "keep ringing" code to
 * write here, that's the whole point of using the real call API.
 *
 * Android does NOT use this file (or callkeep at all) — see
 * src/services/androidDispatchAlert.ts, a notifee full-screen notification instead. iOS
 * keeps CallKit because it's the only way to ring over a locked/killed screen on iOS;
 * Android dropped it because the equivalent telecom permissions (CALL_PHONE,
 * READ_PHONE_STATE, foreground-service camera/microphone) were Google Play "restricted"
 * permissions for a feature that was never placing a real call.
 *
 * NOTE on app size: unlike the account/role-gated JS *screens* elsewhere in this feature,
 * react-native-callkeep and react-native-voip-push-notification are native modules that
 * get compiled into the app binary for EVERY install once added as dependencies — lazily
 * `require()`-ing the JS wrapper (done below) avoids running its setup code for non-
 * dispatcher users, but does not reduce native binary size the way lazy-loading a
 * JS-only dependency (e.g. expo-location) does. There is no way to make CallKit
 * support "binary-optional" in a single build.
 */

let isSetUp = false;

export async function setupCallKeep(): Promise<void> {
  if (Platform.OS !== 'ios' || isSetUp) return;
  const RNCallKeep = require('react-native-callkeep').default;

  await RNCallKeep.setup({
    ios: {
      appName: 'Paltuu Dispatcher',
      supportsVideo: false,
      includesCallsInRecents: false,
    },
  });

  isSetUp = true;
}

/**
 * ⚠️ There is deliberately no `displayIncomingExpressVetCall` here any more.
 *
 * Showing the incoming call from JS is what broke this feature: Apple requires the CallKit
 * report to happen before the PushKit completion handler returns, and JS can never meet
 * that deadline (the event is async, and on a cold start from a killed app there is no JS
 * running at all). Every VoIP push therefore violated the contract — iOS killed the app on
 * arrival and eventually stopped delivering VoIP pushes to it entirely.
 *
 * The call is now reported natively in AppDelegate.swift, generated by
 * plugins/withVoipPushAppDelegate.js, which also passes the job payload through so
 * CallKeep's `didDisplayIncomingCall` event hands JS both the callUUID and the data
 * (see src/services/dispatcherVoipPush.ts). Calling `displayIncomingCall` from JS now
 * would report a SECOND, duplicate call to CallKit — do not add it back.
 */


export function endCallKeepCall(callUUID: string): void {
  try {
    const RNCallKeep = require('react-native-callkeep').default;
    RNCallKeep.endCall(callUUID);
  } catch {
    // CallKeep not set up yet (e.g. app cold-started straight into this from a killed
    // state race) — nothing to end, safe to ignore.
  }
  useIncomingCallStore.getState().clear(callUUID);
}

/**
 * Wires the two events that matter for this feature: answering navigates into the
 * request + attempts the claim, ending just tears down local state (declining a call the
 * dispatcher was never assigned doesn't need a server call — the request just stays
 * `pending_dispatch` for the next dispatcher). Call once, high in the tree (see
 * DispatcherCallProvider) — safe to call multiple times, CallKeep dedupes by handler
 * identity is NOT guaranteed, so the caller is responsible for only calling this once.
 */
export function attachCallKeepListeners(handlers: {
  onAnswer: (payload: IncomingExpressVetCallPayload, callUUID: string) => void;
  onEnd?: (callUUID: string) => void;
}): () => void {
  const RNCallKeep = require('react-native-callkeep').default;

  const onAnswerCall = ({ callUUID }: { callUUID: string }) => {
    const payload = useIncomingCallStore.getState().get(callUUID);
    if (payload) {
      handlers.onAnswer(payload, callUUID);
    }
  };

  const onEndCall = ({ callUUID }: { callUUID: string }) => {
    handlers.onEnd?.(callUUID);
    useIncomingCallStore.getState().clear(callUUID);
  };

  RNCallKeep.addEventListener('answerCall', onAnswerCall);
  RNCallKeep.addEventListener('endCall', onEndCall);

  return () => {
    RNCallKeep.removeEventListener('answerCall', onAnswerCall);
    RNCallKeep.removeEventListener('endCall', onEndCall);
  };
}
